#!/bin/zsh

brew update --all
brew upgrade --all
upgrade.sh

if [ -f ~/.scripts/.epoch ];
then
    rm ~/.scripts/.epoch
    echo `date +"%s"` > ~/.scripts/.epoch
else
    echo `date +"%s"` > ~/.scripts/.epoch
fi


